---
title: "R bootcamp topics"
output:
  html_document:
      toc:  TRUE
      toc_depth: 4
      toc_float: TRUE
      number_section: FALSE
---
<style type="text/css">
h1 { font-size: 26px; }
h2 { font-size: 21px; }
h3 { font-size: 18px; }
</style>

# Slow R: basic introduction to R

This module provides a deliberately slow introduction to R that assumes that you have little or no experience with R and have not worked extensively with other programming languages.

- [Slow R](talks/slow-r.html) (Rick Gilmore) | [Download](talks/slow-r.Rmd)

*Other resources*

- Kelly Black R tutorial: https://www.cyclismo.org/tutorial/R/index.html
- James LeBreton [R introduction](https://psu-psychology.github.io/r-bootcamp/talks/R-Workshop-James.nb.html) (from R Bootcamp 2017) | [Rmd source](https://github.com/psu-psychology/r-bootcamp/blob/master/docs/talks/R-Workshop-James.Rmd)

***

# Multilevel Models and Interactions

- [Intro to MLM and interactions](talks/RBootcamp_MLMInteractions_2019_0820_Final2.html) (Nilam Ram and Mimi Brinberg) | [Rmd](talks/RBootcamp_MLMInteractions_2019_0820_Final2.Rmd)

***
 
# Structural equation modeling

- [Structural equation modeling in lavaan](talks/lavaan_tutorial.html) (Michael Hallquist) | [Rmd](talks/lavaan_tutorial.Rmd) | [Exercise](talks/lavaan_exercise.Rmd)

*Other resources*

- Alison Schreiber We R [lavaan walkthrough](https://quantdev.ssri.psu.edu/tutorials/structural-equation-modeling-r-using-lavaan)
- Michael Hallquist [PSY 597 SEM course in R](https://psu-psychology.github.io/psy-597-sem-sp2019/)
- [lavaan tutorial](http://lavaan.ugent.be/tutorial/index.html)

***

# Dynamical systems analysis using dynr

- Lecture: [Dynamical modeling using dynr](talks/chow_dynr_slides.pdf) (Sy-Miin Chow) | [Zip of all files](data/dynr_demo.zip)
- [Growth curve modeling demo](demos/dynr/GCM_demo.html) | [Rmd](demos/dynr/GCM_demo.Rmd)
- [Process factor analysis demo](demos/dynr/PFAindynr.html) | [Rmd](demos/dynr/PFAindynr.Rmd)
- [Vector autoregressive model demo](demos/dynr/VAR_demo.html) | [Rmd](demos/dynr/VAR_demo.Rmd)

***

# Data wrangling

- [Tidy data and tidyr overview](talks/tidy_data_conceptual.html) (Michael Hallquist) | [Rmd](talks/tidy_data_conceptual.Rmd)
- [dplyr and wrangling walkthrough](talks/dplyr_walkthrough_2019.html) (Michael Hallquist) | [Rmd](talks/dplyr_walkthrough_2019.Rmd)

## Exercises

1. [Review joins tutorial in Rstudio](talks/joins_tutorial_bnj.html) | [Rmd](talks/joins_tutorial_bnj.Rmd)
2. [Complete tidyr exercises](talks/tidyr_exercises.html) | [Rmd](talks/tidyr_exercises.Rmd) | [Key](talks/tidyr_exercises_key.html)
3. [Complete dplyr exercises](talks/bryan_dplyr_exercises.html) | [Rmd](talks/bryan_dplyr_exercises.Rmd)

***

# Data visualization

- [Grammar of graphics](talks/ggplot_grammar.html) | [Rmd](talks/ggplot_grammar.Rmd) (Nate Hall)
- [Basic visualization using ggplot2](talks/data_visualization.html) | [Rmd](talks/data_visualization.Rmd) (Holly Zaharchuk, Rebecca Janis & Alicia Vallorani)
- [Supplemental materials for lecture](talks/data_visualization_supp.html) | [Rmd](talks/data_visualization_supp.Rmd)
- [ggplot2 practice exercise](talks/data_visualization_practice.html) | [Rmd](talks/data_visualization_practice.Rmd)

*Other resources*

- Jenny Bryan [ggplot2 tutorial](https://github.com/jennybc/ggplot2-tutorial) | [Download](https://github.com/jennybc/ggplot2-tutorial/archive/master.zip)
- [ggplot2 documentation](http://ggplot2.tidyverse.org/reference/)
- ggplot2 tutorial that provides useful guidance on detailed formatting: <https://tutorials.iq.harvard.edu/R/Rgraphics/Rgraphics.html>

***

# R-eproducible Science

- [R-eproducible Psychological Science](talks/r-eproducible-science.html) (Rick Gilmore)| [Download Rmd](talks/r-eproducible-science.Rmd).
- [R Markdown example output](talks/bootcamp-survey.html) using our own survey data | [Download Rmd](talks/bootcamp-survey.Rmd)
- Complete APA format manuscript based on `papaja` using the survey data, both in the original R Markdown format [Download Rmd](https://psu-psychology.github.io/r-bootcamp-2018/talks/gilmore-hallquist-bootcamp-2018-papaja.Rmd) version and the final [PDF](https://psu-psychology.github.io/r-bootcamp-2018/talks/gilmore-hallquist-bootcamp-2018-papaja.Rmd) version.

***

# Basic data analyses

- [Basic data analyses in R](talks/data_analyses.html): correlation, regression, ANOVA, categorical data (Dan Albohn, Kayla Brown, Yiming Qian) | [Rmd](talks/data_analyses.Rmd)
- [Data analysis supplemental materials](talks/data_analyses_supp.html) | [Rmd](talks/data_analyses_supp.Rmd)
- [Data analysis practice exercises](talks/data_analyses_practice.html) | [Rmd](talks/data_analyses_practice.Rmd)


# Resources from previous years

## Best practices in R programming

<!-- - Setting up a Github repo as an R project | [Video](mov/rstudio-project-on-github.mp4) -->
<!-- - Using Github within RStudio | [Video](mov/edit-save-commit-push.mp4) -->

*Other resources*

- [Wickham R style guide](http://adv-r.had.co.nz/Style.html)

***

# Correlation and regression in R

- Basic [correlation and regression walkthrough](https://psu-psychology.github.io/r-bootcamp-2018/talks/correlation_regression.html) (Michael Hallquist) | [Rmd](https://psu-psychology.github.io/r-bootcamp-2018/talks/correlation_regression.Rmd)

# ANOVA and categorical data

- Basic [ANOVA and categorical data walkthrough](https://psu-psychology.github.io/r-bootcamp-2018/talks/anova_categorical.html) (Michael Hallquist) | [Rmd](https://psu-psychology.github.io/r-bootcamp-2018/talks/anova_categorical.Rmd)

*Other resources*

- More about the [aov_ez function](http://singmann.org/anova-in-r-afex-may-be-the-solution-you-are-looking-for/)
- Post hoc contrasts in ANOVA using the [afex package](https://cran.r-project.org/web/packages/afex/vignettes/afex_anova_example.html)
- Probing interactions using the [jtools package](https://cran.r-project.org/web/packages/jtools/vignettes/interactions.html)

***

## Exploratory factor analysis

<!-- - [Exploratory factor analysis tutorial](talks/IntroBasicEFA_2018_0815.html) (Nilam Ram) | [zip](zips/ram_efa.zip) | [Slides](talks/RBootcamp_IntroFactorAnalysis_2018_0816.pdf) | [Rmd](talks/IntroBasicEFA_2018_0815.Rmd) | [QuantDev link](https://quantdev.ssri.psu.edu/tutorials/intro-basic-exploratory-factor-analysis) -->

***

## Parallel computing and big data

<!-- - Michael Hallquist [introduction to parallel R](talks/parallel_r.html) | [zip](zips/hallquist_parallel.zip) | [Rmd](talks/parallel_r.Rmd) -->
<!-- - [Example of parallel computation](R/clock_MEG_lmer.R.txt) on large neuroimaging dataset using foreach package | [Download](R/clock_MEG_lmer.R) -->
<!-- - Example of [setting a progress bar in a parallel foreach loop](https://gist.github.com/michaelhallquist/530035827ba46d16900b9f5b0169fb45) | [Download the whole script](R/fitVoxelwiseARMA.R) (for context) -->

*Other parallel computing resources*

- R [parallel package documentation](https://stat.ethz.ch/R-manual/R-devel/library/parallel/doc/parallel.pdf)
- R [doParallel package documentation](https://cran.r-project.org/web/packages/doParallel/vignettes/gettingstartedParallel.pdf)
- Matt Jones [Parallel R tutorial](https://nceas.github.io/oss-lessons/parallel-computing-in-r/parallel-computing-in-r.html)
- Jonathan Dursi 'Beyond Single Core' [tutorial](https://ljdursi.github.io/beyond-single-core-R)

*Other big data resources*

- Rstudio [webinar about big data](https://www.rstudio.com/resources/webinars/working-with-big-data-in-r/)
- Useful big data presentation: <http://www.columbia.edu/~sjm2186/EPIC_R/EPIC_R_BigData.pdf>
- Programming with big data in R (pbdr): <https://pbdr.org>
